### ISSUE TITLE
It failed to install on my machine

### ISSUE THREAD

**Issue by Match-Yang** [neurobin/MT7630E#1]
My machine: ASUS X550V

$uname -r 
3.13.0-37-generic

install log:
...
make[1]:正在离开目录 `/usr/src/linux-headers-3.13.0-37-generic'
make -C /lib/modules/3.13.0-37-generic/build M=/home/match/下载/MT7630E-master/btloader clean
make[1]: 正在进入目录`/usr/src/linux-headers-3.13.0-37-generic'
  CLEAN   /home/match/下载/MT7630E-master/btloader/.tmp_versions
  CLEAN   /home/match/下载/MT7630E-master/btloader/Module.symvers
make[1]:正在离开目录 `/usr/src/linux-headers-3.13.0-37-generic'
make -C /lib/modules/3.13.0-37-generic/build M=/home/match/下载/MT7630E-master/btloader modules
make[1]: 正在进入目录`/usr/src/linux-headers-3.13.0-37-generic'
  CC [M]  /home/match/下载/MT7630E-master/btloader/mt76xx.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/match/下载/MT7630E-master/btloader/mt76xx.mod.o
  LD [M]  /home/match/下载/MT7630E-master/btloader/mt76xx.ko
make[1]:正在离开目录 `/usr/src/linux-headers-3.13.0-37-generic'
update-rc.d: warning: /etc/init.d/load.sh missing LSB information
update-rc.d: see http://wiki.debian.org/LSBInitScripts
 System start/stop links for /etc/init.d/load.sh already exist.
insmod: ERROR: could not insert module /lib/modules/3.13.0-37-generic/kernel/drivers/misc/eeprom/eeprom.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.13.0-37-generic/kernel/drivers/misc/eeprom/eeprom_93cx6.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.13.0-37-generic/kernel/lib/crc-ccitt.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.13.0-37-generic/kernel/net/wireless/cfg80211.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.13.0-37-generic/kernel/net/mac80211/mac80211.ko: File exists
insmod: ERROR: could not insert module ./rt2x00lib.ko: File exists
insmod: ERROR: could not insert module ./rt2x00pci.ko: Unknown symbol in module
insmod: ERROR: could not insert module ./rt2x00mmio.ko: Invalid parameters
insmod: ERROR: could not insert module ./rt2800lib.ko: File exists
insmod: ERROR: could not insert module ./rt2800pci.ko: Invalid parameters
insmod: ERROR: could not insert module ./mt76xx.ko: File exists

when I restart my OS,bluetooth module can work,WIFI can't!

**Comment by Match-Yang** [comment]
when I put an USB wireless device and run $sudo rfkill list all 
it show below:
0: asus-wlan: Wireless LAN
    Soft blocked: no
    Hard blocked: no
1: asus-bluetooth: Bluetooth
    Soft blocked: no
    Hard blocked: no
2: hci0: Bluetooth
    Soft blocked: no
    Hard blocked: no
3: phy0: Wireless LAN
    Soft blocked: no
    Hard blocked: no

but when I disconnect my USB wireless device and run $sudo rfkill list all  again,it show below:
0: asus-wlan: Wireless LAN
    Soft blocked: no
    Hard blocked: no
1: asus-bluetooth: Bluetooth
    Soft blocked: no
    Hard blocked: no
2: hci0: Bluetooth
    Soft blocked: no
    Hard blocked: no
3: phy0: Wireless LAN
    Soft blocked: no
    Hard blocked: yes

**Comment by rbecheras** [comment]
I have the same problem.
Did you finally succed to install the wifi part of the driver @Match-Yang  ?
Here are other people having the same (french ubuntu forum), and no solved too : http://forum.ubuntu-fr.org/viewtopic.php?pid=18430601

**Comment by rbecheras** [comment]
@mdjahidulhamid , do you understand our issue ?
If you understand it, you could explain it briefly to me and I could try to fix it.

**Comment by neurobin** [comment]
poupougnac, forked my repo and made some modifications which is claimed to be efficient and to be removed the overload problem. You can try that if it really works:

https://github.com/poupougnac/MT7630E

**Comment by neurobin** [comment]
The asus laptop is having some serious issue, you can read this bug report if you find any workaround:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1220146

**Comment by neurobin** [comment]
The driver has gone through some drastic changes. If you have this problem with the new version, please open another issue

regards, jahid

**Comment by Match-Yang** [comment]
Okay, thank you
