### ISSUE TITLE
Ubuntu 16.04 and Secure Boot

### ISSUE THREAD

**Issue by cnt0** [neurobin/MT7630E#22]
Today I realised that Ubuntu 16.04 rejects unsigned kernel modules (like this one) if Secure Boot is enabled. How to deal with it? That's what I can suggest:
- disable Secure Boot. Not so good for security, impossible in some cases
- use Secure Boot with our own certificates, i.e. compile kernel manually. Good only for Gentoo users
- push this driver into the kernel source tree. Don't know if it is possible. Looks like there are lots of issues with license, code quality, etc. @kuba-moo, can you make it clear?

**Comment by kuba-moo** [comment]
I don't think this driver is getting upstream anytime soon. I'd try compiling the kernel from sources if I were you. It's not that hard and there is myriad tutorials.

**Comment by dcialdella** [comment]
I solved it using this package
https://github.com/neurobin/MT7630E

download ZIP, unzip, run "install" and reboot.

I have a Asus tp300la.
