### ISSUE TITLE
Wifi OK, bluetooth not identified.

### ISSUE THREAD

**Issue by gcontini** [neurobin/MT7630E#24]
Kernel version: 4.4.0-21-generic #37-Ubuntu SMP
Wifi is working fine. Here is the relevant lspci line:
03:00.0 Network controller: MEDIATEK Corp. MT7630e 802.11bgn Wireless Network Adapter

Bluetooth is not recognized. Attached the output of my lsusb. 
[lsusb.txt](https://github.com/neurobin/MT7630E/files/250622/lsusb.txt)
I guess "Bus 001 Device 005: ID 0489:e080 Foxconn / Hon Hai" is the bluetooth adapter. 
No /dev/hci0 device.

Asus model F555L

**Comment by tobiasBora** [comment]
Hello,

Didi you try this: https://github.com/neurobin/MT7630E/issues/6#issuecomment-196090923 ?

**Comment by gcontini** [comment]
Today i patched the kernel following the comment you mentioned, but still no result.

I also tried to patch mt76xx.c (note, i don't know what i'm doing, i just copied it from the lines above)
around line 1086 i added the following: 

>    /\* Foxconn / Hon Hai */
>         ....
>     { USB_DEVICE_AND_INTERFACE_INFO(0x0489, 0xe080, 0xe0, 0x01, 0x01) },
>     { USB_DEVICE_AND_INTERFACE_INFO(0x0489, 0xe080, 0xff, 0xff, 0xff) },

to match my usb id.
After compiling and inserting the module the `lsusb` command  didn't report the device `FoxConn HonHai` anymore, and a new entry appeared:
`Bus 001 Device 007: ID 0e8d:763f MediaTek Inc.`

Below the related lines from dmesg:

```
[  510.163192] chip id = 76300002
[  510.163298] Firmware file "mt76x0.bin" Found 
[  510.163299] bulk_tx_ep = 2
[  510.163827] mtk_loader: done
[  510.163829] setup_packet in urb: size=8
[  510.163830] 20 00 00 00 00 00 34 00 
           transfer_buffer in urb: size=52
[  510.163833] c3 fc 31 01 00 00 00 00 00 00 00 00 ff fc 03 00 00 00 00 80 8d 0e 3f 76 05 b8 88 00 00 00 00 00 00 3c 5b ef 02 88 ff ff 5e 00 00 00 00 00 00 00 00 00 00 00 
           submit urb:
[  510.163847] usb_send_vendor_hci_cmd: return=0
[  510.163848] mtk_bt_loader_probe: ret = 0
[  510.163885] usbcore: registered new interface driver mtk_bt_loader
[  510.164060] usb_vendor_hci_cmd_complete 
[  510.392477] usb 1-1.6: USB disconnect, device number 5
[  510.392528] mtk_bt_loader_disconnect
[  510.621070] usb 1-1.6: new high-speed USB device number 7 using ehci-pci
[  510.715497] usb 1-1.6: New USB device found, idVendor=0e8d, idProduct=763f
[  510.715500] usb 1-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  510.715502] usb 1-1.6: Product: BT
[  510.715503] usb 1-1.6: Manufacturer: MediaTek
[  510.715504] usb 1-1.6: SerialNumber: 1.0
```

But still no bluetooth ...

**Comment by neurobin** [comment]
@gcontini There's no need to patch the mt76xx.c, foxconn is already added. Just patch the btusb.c.

[Here](https://github.com/neurobin/MT7630E/wiki/Get-bluetooth-working-in-Linux-kernel--with-mt7630e)'s a detailed explanation on how to patch the btusb.c

**Comment by gcontini** [comment]
@Neurobin: I reinstalled a clean version of the kernel and i follow your guide. It didn't work. Here is my lsusb output.

```
Bus 001 Device 005: ID 0489:e080 Foxconn / Hon Hai 
Bus 001 Device 004: ID 0bda:57b5 Realtek Semiconductor Corp. 
Bus 001 Device 003: ID 046d:c019 Logitech, Inc. Optical Tilt Wheel Mouse
Bus 001 Device 002: ID 8087:8001 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by neurobin** [comment]
@gcontini 
[btusb.ko.zip](https://github.com/neurobin/MT7630E/files/322247/btusb.ko.zip)
How about you use my build of btusb. It's for 4.4.0-24 (Ubuntu)

And also reinstall the driver just to be safe.

**Comment by gcontini** [comment]
Hi NeuroBin, i tried your module but it did not work.

I copied it in folder: /lib/modules/4.4.0-24-generic/kernel/drivers/bluetooth/ 
(chmod and chown as other modules)
rebooted. The module was not loaded.

```
  # modprobe btusb
  modprobe: ERROR: could not insert 'btusb': Exec format error

  #dmesg 
  [.....] btusb: disagrees about version of symbol module_layout

  # uname -a
  Linux pc-contini 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

any advice? thanks for your effort anyway... if you have other tries or suggestions please tell me.

I also opened a bug in launchpad for this. Feel free to vote it.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1579318

**Comment by neurobin** [comment]
@gcontini  

I have recently installed Xubuntu 14.04.4 LTS and tried to apply the patch. It didn't work (at first), but after about 3 days (a few shutdown and restart) it started working. This is a peculiar behavior indeed, but I am just happy that it somehow worked. :D.

But with 16.04 it didn't take any time to enable. I can tell you to try one more thing: 
1. Try adding:

``` c
{ USB_DEVICE_AND_INTERFACE_INFO(0x0489, 0xe080, 0xe0, 0x01, 0x01) },
{ USB_DEVICE_AND_INTERFACE_INFO(0x0489, 0xe080, 0xff, 0xff, 0xff) },
```

 like you did before
2. Apply the patch to the kernel (use 4.4.0-24)
1. Do a clean install of the driver and make sure it doesn't show any error like `could not insert module blah blah blah`
2. Do several shutdowns and restarts (or wait for 3 days :laughing: )

**Comment by tobiasBora** [comment]
Do you know if adding the two lines you show here would break bluetooth when the lines aren't usefull ? If no shouldn't it be added in the main repo ?

**Comment by neurobin** [comment]
@tobiasBora : I will add it, or you can add it too with your next pull request.. :+1:

**Comment by tobiasBora** [comment]
Oh you can do it if you want (except if you don't have the time todo it).
For my pull request version 2 I will work on it at the end of the day when I have more free time.

Le 30 juin 2016 10:58:19 GMT+02:00, Md Jahidul Hamid notifications@github.com a écrit :

> @tobiasBora : I will add it, or you can add it too with your next pull
> request.. :+1: 
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/neurobin/MT7630E/issues/24#issuecomment-229602216

## 

TobiasBora

**Comment by gcontini** [comment]
I have good news. I applied the btusb patch using a clean kernel source (4.4.0-28-generic
), i added the two lines above to  mt76xx.c and i have the bluetooth working now. I don't know what went wrong before. 
It should be useful to have them in the standard release.

**Comment by neurobin** [comment]
@gcontini  good to hear :smiley: 
And yes, the two lines are added in new version
