### ISSUE TITLE
Add support for 4.5 kernel

### ISSUE THREAD

**Issue by redianthus** [neurobin/MT7630E#26]
Hi,

I just installed Debian Testing on a friend's computer, wifi wasn't working, I found this driver, but while trying to install it, I ran into some troubles, saying some files were not found.

So, I think it's because 4.5 kernel is not supported yet, thus, I would like to know if you could add support for 4.5 kernel ?

If you think it's not related to the kernel version, I can give you the exact error I had.

Cheers.

**Comment by neurobin** [comment]
I can't do anything If I don't know the exact error messages. So please do post them here.

**Comment by CaptainBloodz** [comment]
Working fine here with 4.5.x.
ASAIR 'make clean" may be required when changing major kernel version, ie 4.4.x to 4.5.x.
Once performed, I usually run "bash ./install".

For the record the above recipe doesn't seem to work for 4.6.x kernel with the latest mt7630e release.

Thks 4 ur attention.

**Comment by tobiasBora** [comment]
Does your bluetooth also work in 4.5 ? It is broken for me, even with the modified lsusb.

Le 17 mai 2016 20:56:59 GMT+02:00, CaptainBloodz notifications@github.com a écrit :

> Working fine here with 4.5.x.
> ASAIKR 'make clean" may be required when changing major kernel version,
> ie 4.4.x to 4.5.x.
> Once performed, I usually run "bash ./install".
> 
> Thks 4 ur attention.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/neurobin/MT7630E/issues/26#issuecomment-219818448

## 

TobiasBora

**Comment by CaptainBloodz** [comment]
@tobiasBora 
Sorry haven't taken the time yet to patch my kernel despite my intention to do it in the future.
Thks 4 the idea of keeping a 4.4.0 around as it seems to be BT 'ready'.

Cheers

**Comment by tobiasBora** [comment]
Hum it's pretty strange, now bluetooth works for me... Maybe I didn't reboot and it's required...

**Comment by redianthus** [comment]
Hi,

Sorry for responding late, I didn't have acces to this computer as it's not mine. My friend just sent me the output of the install script:

```
make -C /lib/modules/`uname -r`/build M=/home/heloise/Bureau/blop/MT7630E/rt2x00 modules
make[1]: *** /lib/modules/4.5.0-1-amd64/build : Aucun fichier ou dossier de ce type. Arrêt.
Makefile:8 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
cp -v firmware/*/* /lib/firmware/
'firmware/BT/mt76x0.bin' -> '/lib/firmware/mt76x0.bin'
'firmware/Wi-FI/MT7650E234.bin' -> '/lib/firmware/MT7650E234.bin'
cp rt2x00/mt7630e.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
cp: impossible d'évaluer 'rt2x00/mt7630e.ko': Aucun fichier ou dossier de ce type
Makefile:16 : la recette pour la cible « install » a échouée
make: *** [install] Erreur 1
modprobe: FATAL: Module mt7630e not found in directory /lib/modules/4.5.0-1-amd64
modprobe: FATAL: Module mt76xx not found in directory /lib/modules/4.5.0-1-amd64
```

**Comment by neurobin** [comment]
@Sancho-Panza That's not caused by mt7630e driver. your friends' system doesn't have the kernel module building environment setup properly. Tell him to install kernel headers first and try again.

**Comment by redianthus** [comment]
Yep', my bad, you're right. After installing kernel headers it works fine ! I thought I did it, sorry for this...
