### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by rbecheras** [neurobin/MT7630E#3]
Here its my output when runing install.sh

Notice that I already runned the script so some files already exists, but I think the important part is that the make fails many time.

Anyone have an explication for that ?

me@myhost:~/MT7630E$ ./install.sh 
make -C /lib/modules/3.16.0-24-generic/build M=/home/me/MT7630E/rt2x00 clean
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-24-generic'
  CLEAN   /home/me/MT7630E/rt2x00/.tmp_versions
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-24-generic'
make -C /lib/modules/3.16.0-24-generic/build M=/home/me/MT7630E/rt2x00 modules
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-24-generic'
  CC [M]  /home/me/MT7630E/rt2x00/rt2x00dev.o
/home/me/MT7630E/rt2x00/rt2x00dev.c: In function ‘MT76x0_WLAN_ChipOnOff’:
/home/me/MT7630E/rt2x00/rt2x00dev.c:1685:17: warning: left-hand operand of comma expression has no effect [-Wunused-value]
     **FUNCTION**, bOn, g_WlanFunCtrl.word,  WlanFunCtrl.word);
                 ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1685:22: warning: left-hand operand of comma expression has no effect [-Wunused-value]
     **FUNCTION**, bOn, g_WlanFunCtrl.word,  WlanFunCtrl.word);
                      ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1685:42: warning: left-hand operand of comma expression has no effect [-Wunused-value]
     **FUNCTION**, bOn, g_WlanFunCtrl.word,  WlanFunCtrl.word);
                                          ^
In file included from /home/me/MT7630E/rt2x00/rt2x00dev.c:27:0:
include/linux/kernel.h:838:22: warning: statement with no effect [-Wunused-value]
 #define **FUNCTION** (**func**)
                      ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1685:5: note: in expansion of macro ‘**FUNCTION**’
     **FUNCTION**, bOn, g_WlanFunCtrl.word,  WlanFunCtrl.word);
     ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1685:61: error: expected ‘;’ before ‘)’ token
     **FUNCTION**, bOn, g_WlanFunCtrl.word,  WlanFunCtrl.word);
                                                             ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1685:61: error: expected statement before ‘)’ token
/home/me/MT7630E/rt2x00/rt2x00dev.c:1801:15: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   **FUNCTION**, g_WlanFunCtrl.word, WlanFunCtrl.word);
               ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1801:35: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   **FUNCTION**, g_WlanFunCtrl.word, WlanFunCtrl.word);
                                   ^
In file included from /home/me/MT7630E/rt2x00/rt2x00dev.c:27:0:
include/linux/kernel.h:838:22: warning: statement with no effect [-Wunused-value]
 #define **FUNCTION** (**func**)
                      ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1801:3: note: in expansion of macro ‘**FUNCTION**’
   **FUNCTION**, g_WlanFunCtrl.word, WlanFunCtrl.word);
   ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1801:53: error: expected ‘;’ before ‘)’ token
   **FUNCTION**, g_WlanFunCtrl.word, WlanFunCtrl.word);
                                                     ^
/home/me/MT7630E/rt2x00/rt2x00dev.c:1801:53: error: expected statement before ‘)’ token
scripts/Makefile.build:257: recipe for target '/home/me/MT7630E/rt2x00/rt2x00dev.o' failed
make[2]: **\* [/home/me/MT7630E/rt2x00/rt2x00dev.o] Error 1
Makefile:1345: recipe for target '_module_/home/me/MT7630E/rt2x00' failed
make[1]: **\* [_module_/home/me/MT7630E/rt2x00] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-24-generic'
Makefile:29: recipe for target 'all' failed
make: **\* [all] Error 2
make -C /lib/modules/3.16.0-24-generic/build M=/home/me/MT7630E/btloader clean
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-24-generic'
  CLEAN   /home/me/MT7630E/btloader/.tmp_versions
  CLEAN   /home/me/MT7630E/btloader/Module.symvers
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-24-generic'
make -C /lib/modules/3.16.0-24-generic/build M=/home/me/MT7630E/btloader modules
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-24-generic'
  CC [M]  /home/me/MT7630E/btloader/mt76xx.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/me/MT7630E/btloader/mt76xx.mod.o
  LD [M]  /home/me/MT7630E/btloader/mt76xx.ko
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-24-generic'
cp: impossible d'évaluer «rt2x00/*.ko»: Aucun fichier ou dossier de ce type
insserv: warning: script 'K01load.sh' missing LSB tags and overrides
insserv: warning: script 'load.sh' missing LSB tags and overrides
insmod: ERROR: could not insert module /lib/modules/3.16.0-24-generic/kernel/drivers/misc/eeprom/eeprom.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.16.0-24-generic/kernel/drivers/misc/eeprom/eeprom_93cx6.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.16.0-24-generic/kernel/lib/crc-ccitt.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.16.0-24-generic/kernel/net/wireless/cfg80211.ko: File exists
insmod: ERROR: could not insert module /lib/modules/3.16.0-24-generic/kernel/net/mac80211/mac80211.ko: File exists
insmod: ERROR: could not load module ./rt2x00lib.ko: No such file or directory
insmod: ERROR: could not load module ./rt2x00pci.ko: No such file or directory
insmod: ERROR: could not load module ./rt2x00mmio.ko: No such file or directory
insmod: ERROR: could not load module ./rt2800lib.ko: No such file or directory
insmod: ERROR: could not load module ./rt2800pci.ko: No such file or directory
insmod: ERROR: could not insert module ./mt76xx.ko: File exists

**Comment by neurobin** [comment]
The driver is officially for only kernel 3.13 and 3.14 series. So you can't install it in 3.16

**Comment by neurobin** [comment]
There are some workaround for this problem and it's being discussed in https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1220146

Denka in that page says

For ubuntu 14.10 after small changes in code downloaded from mediatek site wifi work.

 /rt2x00/rt2800usb.c

line 766 PREPARE_WORK(&rt2x00dev->txdone_work, rt2800usb_work_txdone);
---> INIT_WORK(&rt2x00dev->txdone_work, rt2800usb_work_txdone);

It will work the same way with my package too...

**Comment by neurobin** [comment]
I haven't checked that yet, I will check it and update the package when i get the time, nowadays i am pretty busy :) sorry for my late answer

**Comment by neurobin** [comment]
I use kernel 3.14 in kubuntu 14.04 64 bit, just because 3.14 is a long term supported kernel version,
http://www.kernel.org

**Comment by rbecheras** [comment]
Ok thanks you very much @mdjahidulhamid , your response was quick! not late.
I will try it this way.

If I success I will share it here.
Again, thank you.

**Comment by neurobin** [comment]
The driver has gone through some drastic changes. If you have this problem with the new version, please open another issue

regards, jahid
