### ISSUE TITLE
modprobe: ERROR: could not insert ('mt7630e/mt76xx'): Required key not available

### ISSUE THREAD

**Issue by brunomelofiro** [neurobin/MT7630E#31]
hey so I'm new to ubuntu but no matter what i try i cannot get your driver to work. when i try installing it i get the following:

> bruno@bruno-TP300LDB:~/MT7630E$ sudo ./install
> make -C /lib/modules/`uname -r`/build M=/home/bruno/MT7630E/rt2x00 modules
> make[1]: Entering directory '/usr/src/linux-headers-4.4.0-24-generic'
>   Building modules, stage 2.
>   MODPOST 1 modules
> make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-24-generic'
> make -C /lib/modules/`uname -r`/build M=/home/bruno/MT7630E/btloader modules
> make[1]: Entering directory '/usr/src/linux-headers-4.4.0-24-generic'
>   Building modules, stage 2.
>   MODPOST 1 modules
> make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-24-generic'
> cp -v firmware/_/_ /lib/firmware/
> 'firmware/BT/mt76x0.bin' -> '/lib/firmware/mt76x0.bin'
> 'firmware/Wi-FI/MT7650E234.bin' -> '/lib/firmware/MT7650E234.bin'
> cp rt2x00/mt7630e.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
> cp btloader/mt76xx.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
> depmod
> modprobe: ERROR: could not insert 'mt7630e': Required key not available
> modprobe: ERROR: could not insert 'mt76xx': Required key not available

now im not sure if i am doing anything wrong but any help would be appreciated, and let me know if you need any more info, thanks!

**Comment by neurobin** [comment]
disable Secure Boot (from BIOS menu) and try again. The driver isn't signed and won't work on secure boot.

**Comment by brunomelofiro** [comment]
thank you so much! worked perfectly!
