### ISSUE TITLE
Support for kernel 4.7

### ISSUE THREAD

**Issue by neurobin** [neurobin/MT7630E#37]
To all users/watchers/contributors:

I would appreciate it if anyone would test the [master](https://github.com/neurobin/MT7630E/tree/2.0.7a) or [2.0.7a](https://github.com/neurobin/MT7630E/tree/master) branch in kernel 4.7.*

**Comment by Stolic** [comment]
I just installed 2.0.7a on Fedora 24 with kernel 4.7.2 without any kind of problems. It works for me.
