### ISSUE TITLE
Manjaro problem

### ISSUE THREAD

**Issue by JustDenP** [neurobin/MT7630E#38]
I can not solve the problem . I do not know what to do , I tried to run on different versions of the kernel . 4.6.6. - 1 and 4.4.17-1, manjaro 16.08pre1

[denis@denis-pc MT7630E-release]$ sudo chmod +x install test uninstall bpatch
[sudo] password for denis: 
[denis@denis-pc MT7630E-release]$ sudo ./install
make -C /lib/modules/`uname -r`/build M=/home/denis/Downloads/MT7630E-release/rt2x00 modules
make[1]: Entering directory '/usr/lib/modules/4.4.17-1-MANJARO/build'
make[1]: **\* No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.4.17-1-MANJARO/build'
make: **\* [Makefile:8: all] Error 2
[denis@denis-pc MT7630E-release]$

**Comment by neurobin** [comment]
Did you install the headers?

**Comment by JustDenP** [comment]
I am beginner :) I used Manjaro settings manajer that would upgrade the kernel .

**Comment by glats** [comment]
You cant install this patch, because it work only on debian derivatives
I used to have the same problem finally I installed kali linux and works like perfectly
Kali linux it's 100% recommendable :grin:

**Comment by JustDenP** [comment]
Oh, this is very sad, because only in Manjaro I have no problem with screan tearing and everything else :'c

**Comment by neurobin** [comment]
@JustDenP 

Please install kernel headers (you may search google) before you try to install the driver. The driver should work on Manjaro as far as I am concerned (not sure about the bluetooth patch though).

**Comment by glats** [comment]
It's very difficult try to recompile the kernel on archlinux or derivates, I did try and I can't do it, it is a very tedious process.

I think de best way it's try kali linux, yes, I am persistent, because kali linux works very good instead manjaro linux, I mean that manjaro worked fine but I really wanted the bluetooth works

**Comment by JustDenP** [comment]
I successfully installed the kernel headers as here .
http://paperiniktips.sviluppo-siti-web.com/arch-linux-how-to-find-and-install-the-right-kernel-headers/
pacman -S linux44-headers
But the problem remains

**Comment by JustDenP** [comment]
this problem is solved , thanks :)
https://forum.manjaro.org/t/solucionado-error-al-instalar-driver-wifi-mt7630e/7644

**Comment by glats** [comment]
Yes, now you have wifi but not bluetooth

**Comment by SeanyMCP** [comment]
Hello everyone,

I am using debian stretch (testing) with kernel 4.9.0-3-amd64. wifi works fine and bluetooth works fine with the bpatch.

I wanted to switch back to Manjaro but I'd like to know if I could use the bpatch by replacing the apt-get lines in it with the pacman's -S ? Would that work or am I taking risks ?

**Comment by neurobin** [comment]
@SeanyMCP  
> if I could use the bpatch by replacing the apt-get lines in it with the pacman's -S

Do these commands work in Manjaro?:
```bash
service bluetooth stop #or
systemctl stop bluetooth.service
service bluetooth start #or
systemctl restart bluetooth.service
```
Are these compatible with pacman?:
```bash
apt-get update
apt-get install build-essential linux-headers-$(uname -r)
apt-get source linux-image-$(uname -r)
apt-get build-dep linux-image-$(uname -r)
```
Are the package names same?

**Comment by SeanyMCP** [comment]
I tried them out and the answer is no for both. I'm not qualified enough to adapt the bpatch to arch (I installed Antergos instead of Manjaro in the end) so I'll just stick to Wifi without bluetooth until somebody finds a patch for arch.

**Comment by Jie317** [comment]
Hi,

Just for information, anyone who runs into this problem might very likely be that the installed header is not correct. Reinstalling the header with the version number from "uname -r" can fix the problem.
