### ISSUE TITLE
Driver did not automatically load at startup

### ISSUE THREAD

**Issue by yat-L** [neurobin/MT7630E#39]
i have a ubuntu 16.04 and 4.4.0-28-generic kernel. I download the 2.0.3 release.

After I followed the steps and install the driver, the wireless card works and i can connect to the internet, but after i reboot the computer, the driver stopped working.

**Comment by glats** [comment]
Hi, you can load manually with modprobe or add the line into modprobe file
check this example https://wiki.archlinux.org/index.php/kernel_modules#Automatic_module_handling

**Comment by yat-L** [comment]
@glats  Thanks a lot, It is working now, cheers !!
