### ISSUE TITLE
Can not install on Kali Linux 2016

### ISSUE THREAD

**Issue by HoangMinh1** [neurobin/MT7630E#43]
I am a newbie and I have problem to install Mediatek MT7630E wifi driver for Kali Linux 2016.2. I tried to install it using dkms on live usb persistence in Kali using your project few days ago and it worked. But now, when I tried to install it on my hardware using the same process, but it did't work when I use ./install. 

make -C /lib/modules/`uname -r`/build M=/root/MT7630E/rt2x00 modules
make[1]: **\* /lib/modules/4.6.0-kali1-amd64/build: No such file or directory.  Stop.
Makefile:8: recipe for target 'all' failed
make: **\* [all] Error 2

Also, "dkms" is not recognized when I try "sudo make dkms"

Please help. Thanks

**Comment by neurobin** [comment]
linux kernel headers are missing, install them first. and also the dkms package if you want it.
