### ISSUE TITLE
[Fedora] System Freeze during install

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [neurobin/MT7630E#48]
I'm trying to install release 2.0.8 on my Fedora 24 Kernel 4.7 the system freezes after depmod. I waited long for the completion, but i always have to hard reboot system to make system responsive again. 

Thanks !

**Comment by jayvdb** [comment]
Did the previous release work for you?

**Comment by saurabh-mhaisekar** [comment]
@jayvdb  Yes, it does work but my Wifi disconnects randomly.

**Comment by Pilleo** [comment]
Same here on Solus os with kernel 4.8.10.
It worked with kernel 4.8.2

**Comment by ars3nal** [comment]
The release works, but if we don't follow these steps
- sudo make clean

-sudo make

- sudo ./install

If we skip the first step, only then it freezes.

**Comment by ajitluhach** [comment]
The release works, but if we don't follow these steps

- sudo make clean

- sudo make

- sudo ./install

only then it freezes. Make sure you clean first. 

 

If we skip the first step, only then it freezes

**Comment by neurobin** [comment]
@ars3nal  : This might be better:

```sh
sudo ./uninstall
sudo make clean
sudo ./install
```

**Comment by Pilleo** [comment]
thank you, worked with Solus. Would be nice to add to the manual. Did not think i have to clean everything even on freshly installed system.

**Comment by ajitluhach** [comment]
@neurobin Thanks, i didn't mean to mislead anyone, it just worked for me, i'm quiet new to linux systems, didn't pay much attention to it. Your suggestion made the install clearer. Thanks again

**Comment by yukurt** [comment]
my system freezes when i use the following for installation:

`sudo make dkms`

when i tried the following steps:

`sudo dkms remove -m mt7630e -v 2.1.0 --all`
`sudo ./uninstall`
`sudo make clean`
`sudo make dkms`

the system system still freezes upon reaching the depmod part. i then have to perform a hard reboot.

i'm using asus laptop K555L, Fedora 27 4.15.16-300.fc27.x86_64.
