### ISSUE TITLE
Debian 8 Jessie?

### ISSUE THREAD

**Issue by bencurio** [neurobin/MT7630E#5]
Please try support Debian Jessie! Thanks :-)

Console output:

```
root@Daniel-PC:/tmp/wifid/MT7630E# sh ./install
make -C /lib/modules/`uname -r`/build M=/tmp/wifid/MT7630E/rt2x00 modules
make[1]: Entering directory '/lib/modules/3.16.0-4-amd64/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/3.16.0-4-amd64/build'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2
cp -v firmware/*/* /lib/firmware/
”firmware/BT/mt76x0.bin” -> ”/lib/firmware/mt76x0.bin”
”firmware/Wi-FI/MT7650E234.bin” -> ”/lib/firmware/MT7650E234.bin”
cp rt2x00/mt7630e.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
cp: stat ”rt2x00/mt7630e.ko” sikertelen: Nincs ilyen fájl vagy könyvtár
Makefile:15: recipe for target 'install' failed
make: *** [install] Error 1
modprobe: FATAL: Module mt7630e not found.
modprobe: FATAL: Module mt76xx not found.
```

**Comment by neurobin** [comment]
It seems your kernel module building environment isn't set properly. You need to install and setup certain things before you can build the driver for your kernel.
You can see this <a href="http://forums.debian.net/viewtopic.php?f=5&t=55146">debain forum topic</a> if it helps

**Comment by bencurio** [comment]
Thank you! I replace linux distro to Ubuntu Gnome 14.04 LTS (amd64) and drivers works correctly. But I have a problem. The "ksoftirqd/0" process is use 100% CPU after use wireless network.

My config:

ASUS X750LB
CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
Wireless: MEDIATEK Corp. MT7630e 802.11bgn Wireless Network Adapter
GPU: NVIDIA Corporation GK208M [GeForce GT 740M](rev a1)

![015-06-21 20 03 28](https://cloud.githubusercontent.com/assets/7604637/8272771/ee1fdbc6-1850-11e5-9c9a-2c98ede36d34.jpg)

**Comment by neurobin** [comment]
Can you download it again from https://github.com/neurobin/MT7630E.
It is reported to have solved the CPU problem by others.
