### ISSUE TITLE
Can't install driver on Ubuntu 16.04

### ISSUE THREAD

**Issue by denis-galas** [neurobin/MT7630E#51]
Hello,
First of all thanks for good drivers. But unfortunately I met an issue with it.
After updates on ubuntu 16.04 my wifi just disappeared. I tried to reinstall driver, usually it helps after ubuntu updates but not this time. This time I'm getting this error while installation:

`modprobe: ERROR: could not insert 'mt7630e': Unknown symbol in module, or unknown parameter (see dmesg)`

DMESG says:
`[ 1004.496521] mac80211: Unknown symbol cfg80211_inform_bss_frame_data (err 0)
[ 1004.496532] mac80211: Unknown symbol cfg80211_sched_scan_results (err 0)
[ 1004.496550] mac80211: Unknown symbol cfg80211_rx_assoc_resp (err 0)
[ 1004.496559] mac80211: Unknown symbol cfg80211_rx_unexpected_4addr_frame (err 0)
[ 1004.496581] mac80211: Unknown symbol cfg80211_chandef_dfs_required (err 0)
[ 1004.496589] mac80211: Unknown symbol cfg80211_scan_done (err 0)
[ 1004.496601] mac80211: Unknown symbol cfg80211_sched_scan_stopped (err 0)
[ 1004.496621] mac80211: Unknown symbol cfg80211_remain_on_channel_expired (err 0)
[ 1004.496629] mac80211: Unknown symbol cfg80211_cac_event (err 0)
[ 1004.496657] mac80211: Unknown symbol ieee80211_amsdu_to_8023s (err 0)
[ 1004.496669] mac80211: Unknown symbol cfg80211_ref_bss (err 0)
[ 1004.496680] mac80211: Unknown symbol ieee80211_mandatory_rates (err 0)
[ 1004.496688] mac80211: Unknown symbol ieee80211_chandef_to_operating_class (err 0)
[ 1004.496721] mac80211: Unknown symbol cfg80211_chandef_valid (err 0)
[ 1004.496729] mac80211: Unknown symbol cfg80211_new_sta (err 0)
[ 1004.496754] mac80211: Unknown symbol cfg80211_calculate_bitrate (err 0)
[ 1004.496773] mac80211: Unknown symbol wiphy_new_nm (err 0)
[ 1004.496784] mac80211: Unknown symbol cfg80211_ready_on_channel (err 0)
[ 1004.496795] mac80211: Unknown symbol cfg80211_classify8021d (err 0)
[ 1004.496808] mac80211: Unknown symbol cfg80211_rx_mlme_mgmt (err 0)
[ 1004.496819] mac80211: Unknown symbol wiphy_register (err 0)
[ 1004.496830] mac80211: Unknown symbol cfg80211_put_bss (err 0)
[ 1004.496838] mac80211: Unknown symbol cfg80211_ch_switch_notify (err 0)
[ 1004.496847] mac80211: Unknown symbol cfg80211_tx_mlme_mgmt (err 0)
[ 1004.496858] mac80211: Unknown symbol cfg80211_gtk_rekey_notify (err 0)
[ 1004.496868] mac80211: Unknown symbol cfg80211_check_combinations (err 0)
[ 1004.496876] mac80211: Unknown symbol cfg80211_tdls_oper_request (err 0)
[ 1004.496885] mac80211: Unknown symbol ieee80211_bss_get_ie (err 0)
[ 1004.496898] mac80211: Unknown symbol cfg80211_get_drvinfo (err 0)
[ 1004.496908] mac80211: Unknown symbol cfg80211_assoc_timeout (err 0)
[ 1004.496918] mac80211: Unknown symbol cfg80211_rx_spurious_frame (err 0)
[ 1004.496926] mac80211: Unknown symbol cfg80211_ibss_joined (err 0)
[ 1004.496934] mac80211: Unknown symbol cfg80211_chandef_compatible (err 0)
[ 1004.496944] mac80211: Unknown symbol cfg80211_iter_combinations (err 0)
[ 1004.496955] mac80211: Unknown symbol cfg80211_report_obss_beacon (err 0)
[ 1004.496970] mac80211: Unknown symbol cfg80211_michael_mic_failure (err 0)
[ 1004.496978] mac80211: Unknown symbol cfg80211_reg_can_beacon_relax (err 0)
[ 1004.496986] mac80211: Unknown symbol cfg80211_cqm_pktloss_notify (err 0)
[ 1004.497001] mac80211: Unknown symbol ieee80211_operating_class_to_band (err 0)
[ 1004.497014] mac80211: Unknown symbol cfg80211_del_sta_sinfo (err 0)
[ 1004.497027] mac80211: Unknown symbol wiphy_unregister (err 0)
[ 1004.497040] mac80211: Unknown symbol ieee80211_radiotap_iterator_init (err 0)
[ 1004.497048] mac80211: Unknown symbol cfg80211_notify_new_peer_candidate (err 0)
[ 1004.497056] mac80211: Unknown symbol cfg80211_sched_scan_stopped_rtnl (err 0)
[ 1004.497070] mac80211: Unknown symbol cfg80211_get_bss (err 0)
[ 1004.497084] mac80211: Unknown symbol __ieee80211_get_channel (err 0)
[ 1004.497098] mac80211: Unknown symbol cfg80211_chandef_usable (err 0)
[ 1004.497109] mac80211: Unknown symbol rfc1042_header (err 0)
[ 1004.497117] mac80211: Unknown symbol cfg80211_cqm_beacon_loss_notify (err 0)
[ 1004.497133] mac80211: Unknown symbol cfg80211_mgmt_tx_status (err 0)
[ 1004.497143] mac80211: Unknown symbol cfg80211_ch_switch_started_notify (err 0)
[ 1004.497151] mac80211: Unknown symbol cfg80211_check_station_change (err 0)
[ 1004.497162] mac80211: Unknown symbol cfg80211_reg_can_beacon (err 0)
[ 1004.497173] mac80211: Unknown symbol cfg80211_find_ie (err 0)
[ 1004.497184] mac80211: Unknown symbol cfg80211_unregister_wdev (err 0)
[ 1004.497192] mac80211: Unknown symbol cfg80211_probe_status (err 0)
[ 1004.497201] mac80211: Unknown symbol ieee80211_data_to_8023 (err 0)
[ 1004.497209] mac80211: Unknown symbol cfg80211_stop_iface (err 0)
[ 1004.497218] mac80211: Unknown symbol ieee80211_radiotap_iterator_next (err 0)
[ 1004.497230] mac80211: Unknown symbol ieee80211_channel_to_frequency (err 0)
[ 1004.497238] mac80211: Unknown symbol cfg80211_rx_mgmt (err 0)
[ 1004.497255] mac80211: Unknown symbol ieee80211_hdrlen (err 0)
[ 1004.497267] mac80211: Unknown symbol cfg80211_chandef_create (err 0)
[ 1004.497275] mac80211: Unknown symbol cfg80211_report_wowlan_wakeup (err 0)
[ 1004.497284] mac80211: Unknown symbol ieee80211_get_mesh_hdrlen (err 0)
[ 1004.497294] mac80211: Unknown symbol cfg80211_get_p2p_attr (err 0)
[ 1004.497305] mac80211: Unknown symbol ieee80211_frequency_to_channel (err 0)
[ 1004.497316] mac80211: Unknown symbol cfg80211_shutdown_all_interfaces (err 0)
[ 1004.497325] mac80211: Unknown symbol cfg80211_radar_event (err 0)
[ 1004.497333] mac80211: Unknown symbol bridge_tunnel_header (err 0)
[ 1004.497342] mac80211: Unknown symbol ieee80211_ie_split (err 0)
[ 1004.497352] mac80211: Unknown symbol ieee80211_ie_split_ric (err 0)
[ 1004.497362] mac80211: Unknown symbol cfg80211_unlink_bss (err 0)
[ 1004.497371] mac80211: Unknown symbol wiphy_free (err 0)
[ 1004.497380] mac80211: Unknown symbol cfg80211_cqm_rssi_notify (err 0)
[ 1004.497392] mac80211: Unknown symbol cfg80211_auth_timeout (err 0)
[ 1004.497399] mac80211: Unknown symbol cfg80211_rx_unprot_mlme_mgmt (err 0)
[ 2538.767201] mac80211: Unknown symbol cfg80211_inform_bss_frame_data (err 0)
[ 2538.767212] mac80211: Unknown symbol cfg80211_sched_scan_results (err 0)
[ 2538.767231] mac80211: Unknown symbol cfg80211_rx_assoc_resp (err 0)
[ 2538.767239] mac80211: Unknown symbol cfg80211_rx_unexpected_4addr_frame (err 0)
[ 2538.767262] mac80211: Unknown symbol cfg80211_chandef_dfs_required (err 0)
[ 2538.767270] mac80211: Unknown symbol cfg80211_scan_done (err 0)
[ 2538.767282] mac80211: Unknown symbol cfg80211_sched_scan_stopped (err 0)
[ 2538.767303] mac80211: Unknown symbol cfg80211_remain_on_channel_expired (err 0)
[ 2538.767311] mac80211: Unknown symbol cfg80211_cac_event (err 0)
[ 2538.767338] mac80211: Unknown symbol ieee80211_amsdu_to_8023s (err 0)
[ 2538.767350] mac80211: Unknown symbol cfg80211_ref_bss (err 0)
[ 2538.767361] mac80211: Unknown symbol ieee80211_mandatory_rates (err 0)
[ 2538.767370] mac80211: Unknown symbol ieee80211_chandef_to_operating_class (err 0)
[ 2538.767404] mac80211: Unknown symbol cfg80211_chandef_valid (err 0)
[ 2538.767412] mac80211: Unknown symbol cfg80211_new_sta (err 0)
[ 2538.767436] mac80211: Unknown symbol cfg80211_calculate_bitrate (err 0)
[ 2538.767455] mac80211: Unknown symbol wiphy_new_nm (err 0)
[ 2538.767466] mac80211: Unknown symbol cfg80211_ready_on_channel (err 0)
[ 2538.767477] mac80211: Unknown symbol cfg80211_classify8021d (err 0)
[ 2538.767490] mac80211: Unknown symbol cfg80211_rx_mlme_mgmt (err 0)
[ 2538.767502] mac80211: Unknown symbol wiphy_register (err 0)
[ 2538.767512] mac80211: Unknown symbol cfg80211_put_bss (err 0)
[ 2538.767520] mac80211: Unknown symbol cfg80211_ch_switch_notify (err 0)
[ 2538.767529] mac80211: Unknown symbol cfg80211_tx_mlme_mgmt (err 0)
[ 2538.767540] mac80211: Unknown symbol cfg80211_gtk_rekey_notify (err 0)
[ 2538.767551] mac80211: Unknown symbol cfg80211_check_combinations (err 0)
[ 2538.767558] mac80211: Unknown symbol cfg80211_tdls_oper_request (err 0)
[ 2538.767567] mac80211: Unknown symbol ieee80211_bss_get_ie (err 0)
[ 2538.767580] mac80211: Unknown symbol cfg80211_get_drvinfo (err 0)
[ 2538.767590] mac80211: Unknown symbol cfg80211_assoc_timeout (err 0)
[ 2538.767600] mac80211: Unknown symbol cfg80211_rx_spurious_frame (err 0)
[ 2538.767608] mac80211: Unknown symbol cfg80211_ibss_joined (err 0)
[ 2538.767615] mac80211: Unknown symbol cfg80211_chandef_compatible (err 0)
[ 2538.767626] mac80211: Unknown symbol cfg80211_iter_combinations (err 0)
[ 2538.767636] mac80211: Unknown symbol cfg80211_report_obss_beacon (err 0)
[ 2538.767651] mac80211: Unknown symbol cfg80211_michael_mic_failure (err 0)
[ 2538.767659] mac80211: Unknown symbol cfg80211_reg_can_beacon_relax (err 0)
[ 2538.767667] mac80211: Unknown symbol cfg80211_cqm_pktloss_notify (err 0)
[ 2538.767682] mac80211: Unknown symbol ieee80211_operating_class_to_band (err 0)
[ 2538.767695] mac80211: Unknown symbol cfg80211_del_sta_sinfo (err 0)
[ 2538.767708] mac80211: Unknown symbol wiphy_unregister (err 0)
[ 2538.767721] mac80211: Unknown symbol ieee80211_radiotap_iterator_init (err 0)
[ 2538.767729] mac80211: Unknown symbol cfg80211_notify_new_peer_candidate (err 0)
[ 2538.767737] mac80211: Unknown symbol cfg80211_sched_scan_stopped_rtnl (err 0)
[ 2538.767752] mac80211: Unknown symbol cfg80211_get_bss (err 0)
[ 2538.767766] mac80211: Unknown symbol __ieee80211_get_channel (err 0)
[ 2538.767779] mac80211: Unknown symbol cfg80211_chandef_usable (err 0)
[ 2538.767790] mac80211: Unknown symbol rfc1042_header (err 0)
[ 2538.767798] mac80211: Unknown symbol cfg80211_cqm_beacon_loss_notify (err 0)
[ 2538.767814] mac80211: Unknown symbol cfg80211_mgmt_tx_status (err 0)
[ 2538.767824] mac80211: Unknown symbol cfg80211_ch_switch_started_notify (err 0)
[ 2538.767832] mac80211: Unknown symbol cfg80211_check_station_change (err 0)
[ 2538.767843] mac80211: Unknown symbol cfg80211_reg_can_beacon (err 0)
[ 2538.767854] mac80211: Unknown symbol cfg80211_find_ie (err 0)
[ 2538.767865] mac80211: Unknown symbol cfg80211_unregister_wdev (err 0)
[ 2538.767873] mac80211: Unknown symbol cfg80211_probe_status (err 0)
[ 2538.767882] mac80211: Unknown symbol ieee80211_data_to_8023 (err 0)
[ 2538.767890] mac80211: Unknown symbol cfg80211_stop_iface (err 0)
[ 2538.767898] mac80211: Unknown symbol ieee80211_radiotap_iterator_next (err 0)
[ 2538.767910] mac80211: Unknown symbol ieee80211_channel_to_frequency (err 0)
[ 2538.767918] mac80211: Unknown symbol cfg80211_rx_mgmt (err 0)
[ 2538.767934] mac80211: Unknown symbol ieee80211_hdrlen (err 0)
[ 2538.767946] mac80211: Unknown symbol cfg80211_chandef_create (err 0)
[ 2538.767954] mac80211: Unknown symbol cfg80211_report_wowlan_wakeup (err 0)
[ 2538.767963] mac80211: Unknown symbol ieee80211_get_mesh_hdrlen (err 0)
[ 2538.767973] mac80211: Unknown symbol cfg80211_get_p2p_attr (err 0)
[ 2538.767984] mac80211: Unknown symbol ieee80211_frequency_to_channel (err 0)
[ 2538.767994] mac80211: Unknown symbol cfg80211_shutdown_all_interfaces (err 0)
[ 2538.768003] mac80211: Unknown symbol cfg80211_radar_event (err 0)
[ 2538.768012] mac80211: Unknown symbol bridge_tunnel_header (err 0)
[ 2538.768020] mac80211: Unknown symbol ieee80211_ie_split (err 0)
[ 2538.768031] mac80211: Unknown symbol ieee80211_ie_split_ric (err 0)
[ 2538.768041] mac80211: Unknown symbol cfg80211_unlink_bss (err 0)
[ 2538.768049] mac80211: Unknown symbol wiphy_free (err 0)
[ 2538.768059] mac80211: Unknown symbol cfg80211_cqm_rssi_notify (err 0)
[ 2538.768070] mac80211: Unknown symbol cfg80211_auth_timeout (err 0)
[ 2538.768078] mac80211: Unknown symbol cfg80211_rx_unprot_mlme_mgmt (err 0)`

Kernel version is 4.4.0-57-generic. Hope you'll be able to fix it soon, because life without wifi is much harder)

Thank you.

**Comment by kprkpr** [comment]
Im not using same driver, but I had similar problem as you, and I solved it doing a "sudo modprobe cfg80211" before modprobing the wifi driver (In my case was a 7612u).. Maybe is a "new" dependency in newer kernels?

Try to:
sudo modprobe cfg80211
sudo modprobe mt7630e

**Comment by denis-galas** [comment]
Thanks for answer. But it didn't help me because when I'm running sudo modprobe cfg80211, I'm getting this:
`modprobe: FATAL: Module cfg80211 not found in directory /lib/modules/4.4.0-57-generic`

I'm looking how to install it, but still didn't found any working solution

**Comment by neurobin** [comment]
Did you run the uninstall script before installing again:

```sh
sudo ./uninstall
sudo make clean #if you are running from the same source
```

N.B: I am on Xubuntu 16.04 with `4.4.0-57-generic`, no problem so far, wifi and bluetooth both are wroking...

**Comment by denis-galas** [comment]
yes, I did this. Didn't help me

**Comment by neurobin** [comment]
How about a reinstall from freshly downloaded source:

```sh
sudo ./uninstall #must use sudo and must run this uninstall command
sudo ./install
```

**Comment by denis-galas** [comment]
It's most recent version. Here is latest commit:
commit 35f9a53f6b6d54469fa4fe049ac278f0325d50f7
Author: Md Jahidul Hamid <jahidulhamid@yahoo.com>
Date:   Tue Oct 11 15:11:25 2016 +0600

    fix indentation and update driver version

**Comment by neurobin** [comment]
Just updated the uninstall script.

**Comment by denis-galas** [comment]
Unfortunately same

**Comment by neurobin** [comment]
Hmm, weird. I am on a same system as you, yet I can't reproduce this problem...

**Comment by denis-galas** [comment]
Check if you have latest updates of Ubuntu. I have this problem only after last update

**Comment by evenfrost** [comment]
Got the same error with exact same config after updating Ubuntu.
```bash
sudo ./uninstall
sudo make clean
sudo ./install
```
solved the issue, thanks.

**Comment by neurobin** [comment]
@evenfrost It should. Though you don't need the `make clean` anymore, it's included in the uninstall (latest) script.

**Comment by denis-galas** [comment]
I still have this issue and can't find any solution. 
`sudo ./uninstall`
`sudo ./install`
doesn't help me

**Comment by evenfrost** [comment]
@denis-galas Follow this exact order:
```sh
sudo ./uninstall
sudo make clean
sudo ./install
```
It is `make clean` that helped me to fix this issue.

**Comment by glats** [comment]
Clone the repo again and run the code previously mentioned

```
sudo ./uninstall
sudo make clean
sudo ./install
```

**Comment by denis-galas** [comment]
Thank you very much. I finally have wifi on my laptop!
