### ISSUE TITLE
[Fedora] problem installing the driver 

### ISSUE THREAD

**Issue by MahmoudElghzaly** [neurobin/MT7630E#54]
hi there 
i am noob using linux
i used to use the driver on ubuntu and i hadn't face any problem while installing it 
my wifi card no. is MT7630e
on Fedora i could not install it and it get me that error

> [Elghzaly@syper ~]$ cd ~/Downloads/MT7630E-release
[Elghzaly@syper MT7630E-release]$ sudo chmod +x install
[sudo] password for Elghzaly: 
[Elghzaly@syper MT7630E-release]$ sudo ./install
make -C /lib/modules/`uname -r`/build M=/home/Elghzaly/Downloads/MT7630E-release/rt2x00 modules
make[1]: *** /lib/modules/4.9.8-201.fc25.x86_64/build: No such file or directory.  Stop.
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

i searched for the problem and find out that i should first  run " sudo make clean " first of all 
but that error Appears : 

> [Elghzaly@syper MT7630E-release]$ sudo make clean
make -C /lib/modules/`uname -r`/build M=/home/Elghzaly/Downloads/MT7630E-release/rt2x00 clean
make[1]: *** /lib/modules/4.9.8-201.fc25.x86_64/build: No such file or directory.  Stop.
Makefile:12: recipe for target 'clean' failed
make: *** [clean] Error 2

i do not know what to do 
can any one show me the steps to install the driver ?

**Comment by neurobin** [comment]
You need kernel headers to build drivers. You can ask on Fedora forums how you can setup your system to build drivers.
