### ISSUE TITLE
Wifi disconnection

### ISSUE THREAD

**Issue by Julen10** [neurobin/MT7630E#57]
Im using 4.8.0-37-generic kernel. I installed the last version of drivers and they work fine but sometimes i have disconnections and i must restart the net to have internet again.

I read some similar on another issue but i didnt see any solution. Thanks.

**Comment by CristianoGil** [comment]
happens to me too.

**Comment by Julen10** [comment]
And did you find any solution?

**Comment by CristianoGil** [comment]
Unfortunately not.

**Comment by glats** [comment]
Maybe it's fixed by #42

**Comment by ghost** [comment]
Chiming in to say that I used this driver with kernel 4.4.0-53-generic (i686) on linux mint and didn't have any problems. Thanks to the author! Didn't install the BT part though.

**Comment by Julen10** [comment]
I just installed Ubuntu 17.04 with kernel 4.10.0-20-generic and it works well now. Issue closed.
