### ISSUE TITLE
Unable to Make it work with 4.8 Kernel

### ISSUE THREAD

**Issue by changemenemo** [neurobin/MT7630E#61]
Hi,

It seems that it doesn't work with the last Kernel of Ubuntu 16.10 which is 4.8.x . CAN tout verify please it it's the case? I need your driver for a sais tp300L with this wifi chipset

**Comment by Jpfonseca** [comment]
Please check if the  patch by @apr456 on #58  works .

**Comment by changemenemo** [comment]
Still no luck. How to diagnostic that?

**Comment by changemenemo** [comment]
I had to artificially install the 4.10 and it worked. by chance, the new version for desktop 17.10 have that and since server won't use wifi it is all good i guess
