### ISSUE TITLE
Wifi/BT not work with linux 4.10.3-1

### ISSUE THREAD

**Issue by allardk** [neurobin/MT7630E#62]
Hello,

I updated linux 4.9.11-1 and linux-headers 4.9.11-1 to 4.10.3-1 but after installation, the wifi does'nt work on Antergos. I downgraded to 4.9.11-1 because I need WiFi. Bluetooth would not work on any version. 

Thanks

**Comment by Jpfonseca** [comment]
Try to use the bugfix by @apr456 on #58

**Comment by allardk** [comment]
It's work, thanks :+1:
