### ISSUE TITLE
wifi not working on linux 17.04 and kernel 4.10.0-20-generic

### ISSUE THREAD

**Issue by Richi2293** [neurobin/MT7630E#65]
# System info

Entry | Details
----- | -------
OS | Ubuntu 17.04
Kernel version | 4.10.0-20-generic
New install | no
DKMS | yes

# Devince info

**Device ID:** Bus 003 Device 005: ID 0e8d:763e MediaTek Inc. MT7630e Bluetooth Adapter

**General info:**

```
#block starts
03:00.0 Network controller: MEDIATEK Corp. MT7630e 802.11bgn Wireless Network Adapter
	DeviceName: WLAN
	Subsystem: Hewlett-Packard Company MT7630e 802.11bgn Wireless Network Adapter
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 10
	Region 0: Memory at d0600000 (32-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>

04:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5227 PCI Express Card Reader (rev 01)
	Subsystem: Hewlett-Packard Company RTS5227 PCI Express Card Reader
	Physical Slot: 7
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 29
	Region 0: Memory at d0500000 (32-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: rtsx_pci
	Kernel modules: rtsx_pci

#block ends
```

# What didn't work?
Wi fi does not work

# What did you try?
[please include all details, every small step is important, if already explained above, just use ^^^ or 'see above']

# Error code:

```
#block starts
cp -v firmware/*/* /lib/firmware/
'firmware/BT/mt76x0.bin' -> '/lib/firmware/mt76x0.bin'
'firmware/Wi-FI/MT7650E234.bin' -> '/lib/firmware/MT7650E234.bin'
cp rt2x00/mt7630e.ko /lib/modules/`uname -r`/kernel/drivers/net/wireless/
cp: impossibile eseguire stat di 'rt2x00/mt7630e.ko': File o directory non esistente
Makefile:17: set di istruzioni per l'obiettivo "install" non riuscito
make: *** [install] Errore 1
#block ends
```

I run the command "sudo make install" and returns this error. I think is incompatible the kernel version.

Can be solved?

Thanks

**Comment by glats** [comment]
Did you install kernel headers?
I have the same OS and the only thing I had to do was:

- sudo make clean
- sudo make
- sudo ./install

**Comment by Richi2293** [comment]
Yes, I think it's installed because I was already working. It does not work anymore after I've updated linux headers.

The command "sudo make clean" returns this error:


make -C /lib/modules/`uname -r`/build M=/home/richi/Scaricati/WIFI driver/nuovo/MT7630E-release/rt2x00 clean
make[1]: ingresso nella directory "/usr/src/linux-headers-4.10.0-20-generic"
arch/x86/Makefile:140: CONFIG_X86_X32 enabled but no binutils support
make[1]: ***  Nessuna regola per generare l'obiettivo "driver/nuovo/MT7630E-release/rt2x00".  Arresto.
make[1]: uscita dalla directory "/usr/src/linux-headers-4.10.0-20-generic"
Makefile:13: set di istruzioni per l'obiettivo "clean" non riuscito
make: *** [clean] Errore 2

**Comment by glats** [comment]
Another thing its you must need build-essential package

**Comment by Richi2293** [comment]
I tried to install but it does not work, it always returns error

**Comment by glats** [comment]
The problem it's you have an compilation error. You need to find why when you run make displays this error. It's not problem of the source code.
I find [something](https://askubuntu.com/questions/367838/compiling-error-while-installing-realtek-rtl8111e-in-64-bit-13-10-config-x86-x) that can help you.

**Comment by Richi2293** [comment]
Thank you I solved.

I had a folder with a space in the path where I have the files and I solved by deleting the space. I saw that the commands worked ok so I uninstalled it and reinstalled it and it works.

**Comment by glats** [comment]
Remember close the issue!
