### ISSUE TITLE
Doesn't work at Ubuntu 17 (kernel 4.10.0)

### ISSUE THREAD

**Issue by yuriymarad** [neurobin/MT7630E#71]
# System info

Entry | Details
----- | -------
OS | Ubuntu 17
Kernel version | kernel version here (the output of `4.10.0-19-generic`)
New install | yes
DKMS | yes
Compiler | gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

# Devince info

**Device ID:** Bus 001 Device 005: ID 0e8d:763f MediaTek Inc.

**General info:**

```
#block starts
03:00.0 Network controller: MEDIATEK Corp. MT7630e 802.11bgn Wireless Network Adapter
	Subsystem: Foxconn International, Inc. MT7630e 802.11bgn Wireless Network Adapter
	Control: I/O+ Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 17
	Region 0: Memory at f7900000 (32-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>

04:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8411 PCI Express Card Reader (rev 01)
	Subsystem: ASUSTeK Computer Inc. RTL8411 PCI Express Card Reader
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin B routed to IRQ 26
	Region 0: Memory at f7800000 (32-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: rtsx_pci
	Kernel modules: rtsx_pci

04:00.2 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0a)
	Subsystem: ASUSTeK Computer Inc. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller

#block ends
```

**Bluetooth stats:**

```
#block starts0: asus-wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: asus-bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no

#block ends
```

# What didn't work?
Hello! 
After updating Ubuntu to version 17 I have some problems with WI-FI.
So, I instaled our driver but no result. I have success message after instalation, but WI-FI doesn't working.
Maybe it is new kernel version, I don't know because on previous versions Ubuntu it was working.
Could you help me, please? 
Thanks a lot!

# What did you try?
I just followed step by step in instruction

**Comment by kennethmervin01** [comment]
I think the driver is not compatible in the newer kernel version, I just upgraded the kernel of my Ubuntu 16 to   4.4.0-83-generic and the driver isn't working. It also  make my unit on freeze.

**Comment by neurobin** [comment]
@kennethmervin01 Try applying [this patch](https://github.com/neurobin/MT7630E/issues/68#issuecomment-312358332)

**Comment by neurobin** [comment]
@yuriymarad please download a fresh version of the driver and install, if you get any error post them here.

**Comment by yuriymarad** [comment]
@neurobin Done! All is good now. Thanks a lot!
