### ISSUE TITLE
General crash of system with Ubuntu 14.04.03 and kernel 3.19

### ISSUE THREAD

**Issue by jekyll86** [neurobin/MT7630E#8]
Hi, I have a problem with Ubuntu 14.04 and kernel 3.19. When I try to manage wifi the system freezes, I can't get a console, I have to force shutdown with power button.

**Comment by saulcasalone** [comment]
i've the same problem... have you find some kind of solution?

**Comment by jekyll86** [comment]
No, I had to revert to kernel 3.14
Il 24/ott/2015 07:25 PM, "saulcasalone" notifications@github.com ha
scritto:

**Comment by neurobin** [comment]
Can you guys try this one send feedback:
https://github.com/neurobin/MT7630E/tree/2.0.2
Download the zip and install (don't clone directly).

**Comment by neurobin** [comment]
Can you try the updated version....
