### ISSUE TITLE
Doesn't compiling: rt2x00.h:98:18: error: expected '(' before 'static'

### ISSUE THREAD

**Issue by Scapior** [neurobin/MT7630E#97]
# System info

Entry | Details
----- | -------
OS | Arch Linux
Kernel version | 5.4.8-arch1-1
New install | yes
DKMS | yes
Compiler | $ gcc -v<br>Using built-in specs.<br>COLLECT_GCC=gcc<br>COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper<br>Target: x86_64-pc-linux-gnu<br>Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc<br>Thread model: posix<br>gcc version 9.2.0 (GCC)

# What didn't work?
On the above system configuration driver doesn't compile.

# What did you try?
Commented the line 98 in the file rt2x00.h and that helped to successfully compile.

# Error code:

```
In file included from /home/scapior/Coding/MT7630E/rt2x00/rt2x00dev.c:32:
/home/scapior/Coding/MT7630E/rt2x00/rt2x00.h: In function 'rt2x00_rf_read':
/home/scapior/Coding/MT7630E/rt2x00/rt2x00.h:98:18: error: expected '(' before 'static'
   98 | #define __inline static inline
      |                  ^~~~~~
```

**Comment by valeraradu** [comment]
thank you a lot, commenting the line solved same issue on Ubuntu 20.04

**Comment by neurobin** [comment]
Closing. Should be fixed in new update.

**Comment by neurobin** [comment]
related #102
