### ISSUE TITLE
KALI LINUX 5.4.19 (KALI LINUX LIVE 2020.1B,BASED ON DEBIAN 9) AFTER RUN INSTALL,THERE HAVE TWO ERRORS.

### ISSUE THREAD

**Issue by JUPITER-KOU** [neurobin/MT7630E#98]
# System info
KALI LINUX 5.4.19 (KALI LINUX LIVE 2020.1B,BASED ON DEBIAN 9)
AFTER RUN INSTALL,THERE HAVE TWO ERRORS.

Entry | Details
----- | -------
OS | <put your os name here>
Kernel version | <kernel version here (the output of `uname -r`)>
New install | <yes/no>
DKMS | <yes/no>
Compiler | < include version e.g: gcc-5.4.0 >

# Devince info

**Device ID:** <run `lsusb |grep -i 'mediatek\|foxcon'` to get it (e.g *0e8d:763f*)>
1
**General info:**

```
#block starts
run 'lspci -vv | grep -A20 -i mediatek' and paste the output in this block
#block ends
```

**Bluetooth stats:**

```
#block starts
run 'rfkill list' and paste the output in this block
#block ends
```

# What didn't work?
[please be specific. Do not post excessive error message (only the part that makes sense), you can post the complete error message in the 'Error code' section below.]

# What did you try?
[please include all details, every small step is important, if already explained above, just use ^^^ or 'see above']

# Error code:

```
#block starts
[please include error code in this block]
#block ends
```

# Additional info
[Put any additional information here or leave it blank]

**Comment by neurobin** [comment]
Should be fixed in new update.

**Comment by neurobin** [comment]
related #102
